Update main.tf
Students of our cn-series hackathon found the following issue:

Error: provider not configured: you must configure a path to your kubeconfig
or explicitly supply credentials via the provider block or environment variables.

Whatever version changed caused this changes fixes the issue. As our repo was a fork from this one...